#include <raylib.h>
#include <raymath.h>
#include <algorithm>
#include <cmath>
#include <cctype>
#include <filesystem>
#include <random>
#include <string>
#include <unordered_map>
#include <vector>
namespace fs=std::filesystem;
constexpr float WORLD=3600,HALF=1800,ROAD=90,STREAM=1050,FULL=430,MEDIUM=720,LOW=1050,PI=3.14159265359f;
template<class T>T Clamp(T v,T a,T b){return std::max(a,std::min(v,b));}
float D2(Vector3 a,Vector3 b){float x=a.x-b.x,z=a.z-b.z;return x*x+z*z;} float D(Vector3 a,Vector3 b){return sqrtf(D2(a,b));}
Vector3 Fwd(float y,float p=0){return Vector3Normalize({sinf(y)*cosf(p),-sinf(p),cosf(y)*cosf(p)});} float Ground(float x,float z){return .1f*sinf(x*.004f)*cosf(z*.003f);} 
int Hash(int x,int z){unsigned n=(unsigned)(x*73856093)^(unsigned)(z*19349663);n^=n>>13;n*=0x85ebca6bU;n^=n>>16;return(int)(n&0x7fffffff);}
struct Asset{Model m{};float base=0,h=1;unsigned long long used=0;};
class Assets{public:
 std::vector<std::string>b,l,p,v,r,t;std::unordered_map<std::string,Asset> loaded;std::vector<std::string> q;unsigned long long frame=0;
 static std::string low(std::string s){for(char&c:s)c=(char)std::tolower((unsigned char)c);return s;}
 void scan(){const char*roots[]={"assets 1","assets 2","assets 3","assets"};std::unordered_map<std::string,bool> seen;for(auto root:roots){if(!fs::exists(root))continue;std::error_code e;for(auto it=fs::recursive_directory_iterator(root,fs::directory_options::skip_permission_denied,e);it!=fs::recursive_directory_iterator();it.increment(e)){if(e||!it->is_regular_file())continue;std::string x=it->path().generic_string(),k=low(x);if(low(it->path().extension().string())!=".glb"||seen[k])continue;seen[k]=true;if(k.find("landmark")!=std::string::npos)l.push_back(x);else if(k.find("park")!=std::string::npos)p.push_back(x);else if(k.find("vehicle")!=std::string::npos||k.find("car")!=std::string::npos)v.push_back(x);else if(k.find("veget")!=std::string::npos||k.find("tree")!=std::string::npos||k.find("plant")!=std::string::npos)t.push_back(x);else r.push_back(x);}}auto s=[](auto&x){std::sort(x.begin(),x.end());};s(b);s(l);s(p);s(v);s(r);s(t);}
 const std::vector<std::string>&pool(const std::string&k)const{if(k=="landmark")return l;if(k=="park")return p;if(k=="vehicle")return v;if(k=="prop")return r;if(k=="vegetation")return t;return b;}
 std::string pick(const std::string&k,unsigned seed)const{auto&x=pool(k);return x.empty()?"":x[seed%x.size()];}
 void request(const std::string&x){if(x.empty()||loaded.count(x))return;if(std::find(q.begin(),q.end(),x)==q.end())q.push_back(x);}
 void tick(){++frame;if(!q.empty()){std::string x=q.front();q.erase(q.begin());if(fs::exists(x)){Model m=LoadModel(x.c_str());if(m.meshCount){BoundingBox bb=GetModelBoundingBox(m);Asset a;a.m=m;a.h=std::max(.1f,bb.max.y-bb.min.y);a.base=-bb.min.y;a.used=frame;loaded.emplace(x,a);}}}while(loaded.size()>64){auto z=loaded.begin();for(auto i=loaded.begin();i!=loaded.end();++i)if(i->second.used<z->second.used)z=i;UnloadModel(z->second.m);loaded.erase(z);}}
 bool ready(const std::string&x)const{return loaded.count(x)>0;}
 void draw(const std::string&x,Vector3 p,float h,float yaw){auto i=loaded.find(x);if(i==loaded.end()){request(x);return;}i->second.used=frame;float s=h/i->second.h;DrawModelEx(i->second.m,{p.x,p.y+i->second.base*s,p.z},{0,1,0},yaw*180/PI,{s,s,s},WHITE);}
 void unload(){for(auto&x:loaded)UnloadModel(x.second.m);loaded.clear();q.clear();}
};
enum Q{FAR,LO,MED,FULLQ};Q quality(float d){return d<FULL?FULLQ:d<MEDIUM?MED:d<LOW?LO:FAR;}
struct Obj{std::string a;Vector3 p;float h,y;bool landmark=false;};
struct Car{Vector3 p;float y=0,s=0;bool police=false;std::string a;};
struct Game{Vector3 p{0,1,80};float yaw=0,pitch=.16f,health=100,armor=50,fire=0,wantedT=0;int cash=500,wanted=0;bool car=false;Car*cp=nullptr;std::vector<Car>cars;std::vector<Obj>map;};
std::string district(float x,float z){if(z>1350)return"water";if(fabs(x)>1350||fabs(z)>1650)return"out";if(fabs(x)<360&&fabs(z)<450)return"downtown";if(x>450&&z<700)return"commercial";if(x<-450&&z<700)return"industrial";if(fabs(x)>500&&z>450)return"park";return"residential";}
void makeMap(Game&g,Assets&a){for(int x=-20;x<20;x++)for(int z=-20;z<20;z++){int seed=Hash(x,z);float bx=x*ROAD+45,bz=z*ROAD+45;std::string d=district(bx,bz);if(d=="water")continue;if(d=="park"&&seed%3==0&&!a.p.empty()){g.map.push_back({a.pick("park",seed),{bx,Ground(bx,bz),bz},15+(seed%8),float(seed%360),false});}else{int n=2+seed%3;for(int j=0;j<n;j++){float px=bx+(j%2)*34-17+(seed%7-3),pz=bz+(j/2)*30-15;float h=d=="downtown"?48+seed%52:d=="commercial"?24+seed%34:d=="industrial"?12+seed%20:8+seed%18;g.map.push_back({a.pick("building",seed+j*31),{px,Ground(px,pz),pz},(float)h,float((seed+j*71)%360),false});}}if(seed%4==0)g.map.push_back({a.pick("prop",seed+71),{bx+30,Ground(bx+30,bz+24),bz+24},3.5f,float(seed%360),false});if(seed%3==0)g.map.push_back({a.pick("vegetation",seed+151),{bx-30,Ground(bx-30,bz-28),bz-28},5,float(seed%360),false});}
 const Vector3 spots[]={{0,0,0},{-180,0,-180},{600,0,-300},{-650,0,-100},{300,0,850},{-800,0,850},{900,0,900}};for(size_t i=0;i<a.l.size()&&i<7;i++){Vector3 p=spots[i];p.y=Ground(p.x,p.z);g.map.push_back({a.l[i],p,62+18*(float)(i%4),float(i*51),true});}}
void traffic(Game&g,Assets&a){std::mt19937 r(4242);std::uniform_real_distribution<float>d(-1600,1600);for(int i=0;i<70;i++){Car c;bool h=i%2==0;float lane=(i%18-9)*90;c.p=h?Vector3{d(r),.2f,lane}:Vector3{lane,.2f,d(r)};c.y=h?(i%4<2?0:PI):(i%4<2?PI*.5f:-PI*.5f);c.s=5+i%8;c.police=i<6;c.a=a.pick("vehicle",i*17+3);g.cars.push_back(c);}}
void updateCars(Game&g,float dt){for(auto&c:g.cars){if(&c==g.cp)continue;c.p.x+=sinf(c.y)*c.s*dt;c.p.z+=cosf(c.y)*c.s*dt;if(c.p.x>HALF)c.p.x=-HALF;if(c.p.x<-HALF)c.p.x=HALF;if(c.p.z>HALF)c.p.z=-HALF;if(c.p.z<-HALF)c.p.z=HALF;}if(g.car&&g.cp){auto&c=*g.cp;float a=(IsKeyDown(KEY_W)?24.f:0)-(IsKeyDown(KEY_S)?18.f:0);c.s=Clamp(c.s+a*dt,-12.f,32.f);c.s*=powf(.985f,dt*60);float st=(IsKeyDown(KEY_D)?1.f:0)-(IsKeyDown(KEY_A)?1.f:0);c.y+=st*1.9f*dt*(.25f+fabs(c.s)/20);c.p.x+=sinf(c.y)*c.s*dt;c.p.z+=cosf(c.y)*c.s*dt;g.p=c.p;}}
void updatePlayer(Game&g,float dt){if(g.car)return;float sp=IsKeyDown(KEY_LEFT_SHIFT)?8:4.5;Vector3 f=Fwd(g.yaw),r=Vector3Normalize(Vector3CrossProduct(f,{0,1,0})),v{};if(IsKeyDown(KEY_W))v+=f;if(IsKeyDown(KEY_S))v-=f;if(IsKeyDown(KEY_A))v-=r;if(IsKeyDown(KEY_D))v+=r;if(Vector3Length(v)>.1f){v=Vector3Normalize(v)*sp;g.p+=v*dt;g.yaw=atan2f(v.x,v.z);}g.p.x=Clamp(g.p.x,-1770.f,1770.f);g.p.z=Clamp(g.p.z,-1770.f,1770.f);g.p.y=Ground(g.p.x,g.p.z)+1;}
void enterCar(Game&g){if(!IsKeyPressed(KEY_E))return;if(g.car){g.car=false;g.cp=nullptr;g.p.x+=3;return;}float best=100;Car*c=nullptr;for(auto&x:g.cars){float d=D2(g.p,x.p);if(d<best){best=d;c=&x;}}if(c){g.car=true;g.cp=c;c->s=0;}}
void shoot(Game&g){if(g.fire>0||!IsMouseButtonDown(MOUSE_BUTTON_LEFT))return;g.fire=.16f;g.wanted=std::min(5,g.wanted+1);g.wantedT=18;}
void police(Game&g,float dt){if(g.wanted<=0)return;g.wantedT-=dt;if(g.wantedT<=0){g.wanted--;g.wantedT=10;}for(auto&c:g.cars)if(c.police){Vector3 t=g.p-c.p;float d=sqrtf(t.x*t.x+t.z*t.z);if(d<850){c.y=atan2f(t.x,t.z);c.s=14+g.wanted*2;}}}
bool visible(const Camera3D&c,Vector3 p,float d){if(d>LOW)return false;Vector3 to=Vector3Normalize(p-c.position),look=Vector3Normalize(c.target-c.position);return D2(p,c.position)<FULL*FULL||Vector3DotProduct(to,look)>-.25f;}
void drawMap(Game&g,Assets&a,const Camera3D&c){for(auto&i:g.map){float d=D(g.p,i.p);Q q=quality(d);if(q==FAR||!visible(c,i.p,d))continue;if(q==LO&&!i.landmark){if(!a.ready(i.a))a.request(i.a);else a.draw(i.a,i.p,i.h,i.y);continue;}if(q==MED&&!a.ready(i.a))a.request(i.a);else if(q!=FAR&&a.ready(i.a))a.draw(i.a,i.p,i.h,i.y);}for(auto&v:g.cars){float d=D(g.p,v.p);if(d>LOW||!visible(c,v.p,d))continue;if(a.ready(v.a))a.draw(v.a,v.p,2.2f,v.y);else a.request(v.a);}}
void hud(Game&g,Assets&a){DrawRectangle(20,20,400,108,{7,10,14,225});DrawText("GROKTASTIC",38,33,28,WHITE);DrawText(TextFormat("$ %d   HP %d   ARMOR %d",g.cash,(int)g.health,(int)g.armor),38,70,18,WHITE);for(int i=0;i<5;i++)DrawRectangle(310+i*14,100,10,10,i<g.wanted?Color{215,70,55,255}:Color{55,59,65,255});DrawText(TextFormat("STREAM %d/64  QUEUE %d",(int)a.loaded.size(),(int)a.q.size()),GetScreenWidth()-190,20,13,WHITE);DrawText(g.car?"WASD drive | E exit | LMB fire":"WASD move | SHIFT sprint | E enter | LMB fire",20,GetScreenHeight()-22,16,WHITE);}
int main(){SetConfigFlags(FLAG_MSAA_4X_HINT|FLAG_VSYNC_HINT|FLAG_WINDOW_RESIZABLE);InitWindow(1600,900,"Groktastic");SetTargetFPS(60);DisableCursor();Assets a;a.scan();Game g;traffic(g,a);makeMap(g,a);Camera3D c{};c.up={0,1,0};c.fovy=65;c.projection=CAMERA_PERSPECTIVE;while(!WindowShouldClose()){float dt=std::min(GetFrameTime(),.033f);a.tick();g.fire=std::max(0.f,g.fire-dt);Vector2 m=GetMouseDelta();g.yaw+=m.x*.0028f;g.pitch=Clamp(g.pitch-m.y*.0022f,-1.f,.75f);enterCar(g);updatePlayer(g,dt);updateCars(g,dt);shoot(g);police(g,dt);Vector3 focus=g.car&&g.cp?g.cp->p+Vector3{0,1.3f,0}:g.p;c.position=focus+Fwd(g.yaw,0)*-10.5f+Vector3{0,4.8f,0};c.target=focus+Fwd(g.yaw,g.pitch)*12;BeginDrawing();ClearBackground({104,124,145,255});BeginMode3D(c);DrawPlane({0,-.1f,0},{WORLD,WORLD},{39,54,43,255});for(float q=-HALF;q<=HALF;q+=ROAD){DrawCube({0,-.01f,q},WORLD,.13f,17,{31,34,37,255});DrawCube({q,0,0},17,.13f,WORLD,{31,34,37,255});}drawMap(g,a,c);if(!g.car){DrawCylinder({g.p.x,.9f,g.p.z},.32f,.38f,1.7f,10,{38,43,51,255});DrawSphere({g.p.x,1.95f,g.p.z},.31f,{196,151,112,255});}EndMode3D();hud(g,a);EndDrawing();}a.unload();CloseWindow();}
